services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes
